  on:
  push:
    branches:
      - main
jobs:
runs-on: self-hosted
  deploy:
    steps:
      - name: Update repository
        continue-on-error: true
        run: git pull
      - name: Restart docker
        run: docker-compose up -d --build 
