on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update repo
        continue-on-error: true
        run: git pull
      - name: Go to the working dir
        run: cd /var/work/exchange_pwa/templates
      - name: Rebuild and restart docker
        run: docker-compose up -d --build
